# Generated by Django 3.1.7 on 2021-03-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post',
            field=models.TextField(default='Hello I am empty inside!'),
            preserve_default=False,
        ),
    ]
